{
 "title": "Solophy_3_pcap",
 "time": { "from": "2019-03-22T16:36:44.025Z", "to": "2019-03-22T16:39:27.914Z" },
 "panels": [
  {
   "title": "Elevation on the Path ",
   "type": "graph",
   "description": "Hovering over the values shows the corresponding position of the vehicle on map",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "lengthm", "label": "Elevation" }
   ],
   "targets": [
    {
     "alias": "Altitude",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"5_Altitude\" FROM \"CAMessage\" WHERE \"1_ID\" = 3904",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Path of Vehicle 3904",
   "type": "pr0ps-trackmap-panel",
   "gridPos": { "h": 15, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"3_Latitude\" , \"4_Longitude\" FROM \"CAMessage\" WHERE \"1_ID\"=3904",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 11, "w": 16, "x": 0, "y": 10 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT * FROM \"CAMessage\" ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average Speed",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 17, "y": 15 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"6_Speed\"  FROM \"CAMessage\" WHERE \"1_ID\" = 3907",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Yaw Rate",
   "type": "graph",
   "description": "Red line can be adjusted to indicate critical threshold ",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "none", "label": "Yaw Rate [deg/sec]" }
   ],
   "targets": [
    {
     "alias": "Yaw Rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"YawRate\" FROM \"CAMessage\" WHERE \"1_ID\"  = 3904",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Period",
   "type": "singlestat",
   "description": "The total time value do not add up to the actual time because captured messages without Geo-networking fields have been removed",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 25 },
   "format": "dtdurationms",
   "valueName": "total",
   "targets": [
    {
     "alias": "total time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"2_GenerationTime\")/1000 FROM \"CAMessage\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total number of CAMs sent by 3904",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 30 },
   "format": "locale",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT COUNT(\"1_ID\") FROM \"CAMessage\" WHERE \"1_ID\" = 3904",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Number of CAMs sent by 3907",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 30 },
   "format": "locale",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT COUNT(\"1_ID\") FROM \"CAMessage\" WHERE \"1_ID\" = 3907",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}