{
 "title": "ROC_1",
 "time": { "from": "2019-06-04T13:28:34.635Z", "to": "2019-06-04T13:35:13.188Z" },
 "panels": [
  {
   "title": "Capture Data of roc_pcap for vehicle ID: 3907",
   "type": "table",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT * FROM \"CAMessage\" WHERE \"1_ID\" = 3907",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Path of Vehicle 3907 , Data taken from roc_pcap",
   "type": "pr0ps-trackmap-panel",
   "gridPos": { "h": 17, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"3_Latitude\",\"4_Longitude\" FROM \"CAMessage\" WHERE \"1_ID\"=3907",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Data from roc_pcap",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"6_Speed\") FROM \"CAMessage\" WHERE \"1_ID\" = 3907",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Speed Values for 3903 v 3907",
   "type": "graph",
   "description": "There are missing points because data is not registered for the corresponding time instances",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "3903",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"6_Speed\" FROM \"CAMessage\" WHERE \"1_ID\" = 3903",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "3907",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"6_Speed\"  FROM \"CAMessage\" WHERE \"1_ID\" = 3907 ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Data from roc_pcap",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 9, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"6_Speed\") FROM \"CAMessage\" WHERE \"1_ID\" = 3903",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Capture Data of roc_pcap for vehicle ID: 3903",
   "type": "table",
   "description": "This panel shows the data belonging to station ID : 3, speed values are classified arbitrarily (10,20,30).",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 16 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  * FROM \"CAMessage\" WHERE \"1_ID\" = 3903",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Path of Vehicle 3903, Data taken from roc_pcap",
   "type": "pr0ps-trackmap-panel",
   "gridPos": { "h": 18, "w": 11, "x": 13, "y": 17 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"3_Latitude\",\"4_Longitude\" FROM \"CAMessage\" WHERE \"1_ID\"=3903",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Capture Data of roc_pcap",
   "type": "table",
   "description": "This table shows some information about 3 stations, pulled from the roc_pcap capture. Vehicle IDs have been color coded and speed values are classified arbitrarily.\nSome pages display no information this is due to the malformed packets , this error is shown on wireshark as well",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 24 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT * FROM \"CAMessage\" ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}